# Generated by 'ukvm-configure blk net gdb dumpcore fpga'
# Using compiler 'cc', target 'x86_64-linux-gnu'

.BEGIN: ; @echo -e Warning: $(MAKEFILE) requires GNU make.\\nWarning: Attempting to build with \"gmake -f $(MAKEFILE) $(.TARGETS)\" for you now. && gmake -f $(MAKEFILE) $(.TARGETS)

.PHONY: all
all: ukvm-bin

UKVM_CC=cc
UKVM_CFLAGS=-Wall -Werror -std=c99 -O2 -g  -DUKVM_MODULE_BLK -DUKVM_MODULE_NET -DUKVM_MODULE_GDB -DUKVM_MODULE_DUMPCORE -DUKVM_MODULE_FPGA
UKVM_LDFLAGS=
UKVM_LDLIBS=-L${XILINX_XRT}/lib -lOpenCL -lpthread -lrt -lstdc++
UKVM_CPP=g++

FUNKY_CPP=$(UKVM_CPP)
FUNKY_CPPFLAGS=-Wall -O0 -g -std=c++11
# FUNKY_INCLUDES=-I${XILINX_XRT}/include/ -I${XILINX_VIVADO}/include/ 
FUNKY_INCLUDES=-I${XILINX_XRT}/include/ 

UKVM_OBJS= _build-ukvm/ukvm_core.o _build-ukvm/ukvm_elf.o _build-ukvm/ukvm_main.o _build-ukvm/ukvm_module_blk.o _build-ukvm/ukvm_module_net.o _build-ukvm/ukvm_module_gdb.o _build-ukvm/ukvm_module_dumpcore.o _build-ukvm/ukvm_module_fpga.o _build-ukvm/ukvm_hv_kvm.o _build-ukvm/ukvm_hv_kvm_x86_64.o _build-ukvm/ukvm_cpu_x86_64.o
UKVM_HEADERS= /home/koshiba/unikernel/funky-solo5/ukvm/ukvm.h /home/koshiba/unikernel/funky-solo5/ukvm/ukvm_guest.h /home/koshiba/unikernel/funky-solo5/ukvm/ukvm_cc.h /home/koshiba/unikernel/funky-solo5/ukvm/ukvm_hv_kvm.h /home/koshiba/unikernel/funky-solo5/ukvm/ukvm_cpu_x86_64.h

FUNKY_OBJS= _build-funky/funky_fpga_host.o _build-funky/funky_xcl2.o
FUNKY_HEADERS= /home/koshiba/unikernel/funky-solo5/ukvm/funky_fpga_host.h /home/koshiba/unikernel/funky-solo5/ukvm/funky_xcl2.hpp

$(UKVM_OBJS) $(FUNKY_OBJS): $(UKVM_HEADERS) $(FUNKY_HEADERS) 

_build-ukvm:
	mkdir -p _build-ukvm

_build-funky:
	mkdir -p _build-funky

_build-ukvm/ukvm_%.o: /home/koshiba/unikernel/funky-solo5/ukvm/ukvm_%.c $(MAKEFILE_LIST) | _build-ukvm
	$(UKVM_CC) $(UKVM_CFLAGS) -c $< -o $@

_build-funky/funky_%.o: /home/koshiba/unikernel/funky-solo5/ukvm/funky_%.cpp $(MAKEFILE_LIST) | _build-funky
	$(FUNKY_CPP) $(FUNKY_CPPFLAGS) $(FUNKY_INCLUDES) -c $< -o $@

ukvm-bin: $(UKVM_OBJS) $(FUNKY_OBJS) $(MAKEFILE_LIST)
	$(UKVM_CPP) $(UKVM_LDFLAGS) -o $@ $(UKVM_OBJS) $(FUNKY_OBJS) $(UKVM_LDLIBS)

.PHONY: ukvm-clean
ukvm-clean:
	rm -rf _build-ukvm
	rm -rf _build-funky
	rm -f ukvm-bin
